### PR TITLE
Implemented Access behaviour for Ets.Set.KeyValueSet.

### PR DESCRIPTION
**Pull request by am-kantox**
ETS might and should be used as a backend for anything requiring `Access` behaviour only.

This is the implementation of `Access` behaviour for both `Ets.Set` and `Ets.Bag`.

### CODE REVIEW

**Comment by bitwalker** [comment]
You've done a good job with this PR! However, while you can technically implement `Access` for ETS (as you've demonstrated), I would argue that it is not correct to do so. The values returned don't match what is typically expected by the protocol. For example, I notice that you have no tests for nested keys, e.g. `get_in(set, [:a, :b])` - the reason as I'm sure you probably found, is that it doesn't work; `get_in(set, [:a])` returns a tuple of the key _and_ value, whereas `Access` implementations produce just the value (thus letting you navigate arbitrarily deep into a structure). This violates the intuition one has about using Access on a data structure.

To prove my point, let's take an example that one might reasonable expect would work with nested keys, using our intuition about Access and some of the built-in types:

```elixir
# With Map (MapSet doesn't implement Access)
set = Map.new([{:a, %{:b => :c}}])
:c = get_in(set, [:a, :b])

# With List
set = [{:a, %{:b => :c}}]
:c = get_in(set, [:a, :b])

# With ETS
set = Set.new(keypos: 1)
Set.put!(set, [{:a, %{:b => :c}}])
:c = get_in(set, [:a, :b])
** (FunctionClauseError) ..snip..
```

I don't think it is a good idea to implement Access for ETS, as it has different semantics than other implementations of the protocol. I think it is notable that MapSet doesn't implement Access either, when it technically could, but since the semantics are not correct, it does not. I think the fact that the behavior does not match other types is a strong signal that Access is not a good fit for ETS.

That's my two cents anyway.

**Comment by am-kantox** [comment]
/to @bitwalker 

> I notice that you have no tests for nested keys [...] the reason as I'm sure you probably found [...]

The reason is I made an architectural mistake and I'm happy to admit it. I surely had had some good reason to decide to return the whole tuple, but it makes zero sense since `Keyword` discards key in `Access` implementation, so should do we.

> I don't think it is a good idea to implement Access for ETS [...]

I could not disagree more and it surely has the absolute semantics for the `Access` implementation. Please don’t be fooled my first _wrong_ attempt. You were absolutely correct, we should drop the key when returning the result, and it’s easy—please check my sequential commit (the build fails in `Travis` for the reason that is beyond my understanding.)

> I think it is notable that `MapSet` doesn't implement `Access` either [...]

Neither does `List`, but the reason is _not_ they have wrong semantics (they have a perfect one,) if we had arrays in _erlang_, and `MapSet` was built on top of an array, it surely was to implement `Access`. The actual reason is linked list cannot implement `Access` in `O(1)`, and `Access` must run in a fixed time.

Now the behaviour perfectly matches other types. Please re-think your ¢2 :)

**Comment by bitwalker** [comment]
I actually think this might be worse, as the value being returned does not match the value stored.

The reason why Keyword "discards" the key is because the value is not actually the tuple, but the second element in the tuple, and the tuple is just a representation detail.

This is _not_ true of ETS, where the key is often part of the value itself. Your tests demonstrate this, as there is no key/value semantics to what is stored in the set/bag, just values that happen to have a key-like element for lookups. You could implement Access for the KeyValueSet abstraction, but not for Set and Bag.

> Neither does `List`

Good point, only Keyword does, but Keywords _are_ lists, and the reason why lists in general don't implement Access has nothing to do with algorithmic complexity, but rather because lists don't have any key/value semantics outside of Keyword lists. This is much like this library, where only one abstraction actually has the key/value semantics we expect.

> Now the behaviour perfectly matches other types 

It doesn't unfortunately, so I still maintain that Access should not be implemented for these types. I think implementing for KeyValueSet is fine though, so I would suggest refactoring the PR to target that type instead.

**Comment by TheFirstAvenger** [comment]
@am-kantox Thank you for your work on this PR. I agree with @bitwalker that this feature would be perfect for the KeyValueSet module, but not for the base Set/Bag modules.

To give you a bit of insight into the history of Ets, my first pass looked much more like KeyValueSet than the current Set/Bag modules. @bitwalker correctly pointed out that combining both wrapping :ets and changing the core method you interact with it (key/value instead of record) would confuse and degrade the ability to use Ets as simply a wrapper around the ets library, maintaining the record concept (which more veteran :ets users might prefer). The design decision was made to make Set/Bag basic wrappers that added only error handling and other Elixir goodness, but maintained the concept of key/record instead of key/value. The KeyValueSet was then added to allow abstraction of the record concept into a key/value store.

Because of this, adding the Access protocol to KeyValueSet and not the base Set/Bag implementations (even in the normalizing form you used in the second commit) should not be seen as being relegated to a lesser form but instead the opposite, added to the improved version.

If you could revert the second commit, apply the access protocol to the KeyValueSet, remove the version bump (i'll push a new version myself) and then add a .dialyzer_ignore.exs file to the root of the project (with an empty list in it, sorry about that, checking on what happened there now), I can merge it.

Again, thanks for the awesome PR!

**Comment by am-kantox** [comment]
OK, you have finally convinced me. Will do.

**Comment by am-kantox** [comment]
During the implementation of `Access` for `KeyValueSet` I have accidentally fixed a bug with a delegation of `delete/2` and `delete_all/1` to `Set`. These functions are supposed to return `KeyValueSet`; delegated were returning `Set` instead.

**Comment by TheFirstAvenger** [comment]
🎖❤️⭐️⚪️⭐️💙🎖

**Comment by TheFirstAvenger** [comment]
https://hex.pm/packages/ets/0.7.0

**Pull request merged**
